name: Code Style JavaScript

on: [ workflow_call ]

jobs:
  test-javascript:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install npm dependencies
      run: npm install

    - name: Run npm tests
      run: npm run test-script
