name: Code Style PHP

on: [ workflow_call ]

jobs:
  test-php:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["7.3", "7.4"]

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
      with:
        php_version: ${{ matrix.php_version }}
    - name: Run composer test
      uses: php-actions/composer@v6
      with:
        php_version: ${{ matrix.php_version }}
        command: run-script
        args: test

  test-php-experimental:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["8.0", "8.1", "8.2"]

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
      with:
        php_version: ${{ matrix.php_version }}
    - name: Run composer test
      uses: php-actions/composer@v6
      with:
        php_version: ${{ matrix.php_version }}
        command: run-script
        args: test

    continue-on-error: true
