name: Code Style PHP

on: [ workflow_call ]

jobs:
  test-php:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PHP_VERSION: ["7.3", "7.4"]

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
      with:
        php_version: ${{ matrix.PHP_VERSION }}

    - name: Run composer tests
      run: composer test

  test-php-experimental:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PHP_VERSION: ["8.0", "8.1", "8.2-rc"]

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
      with:
        php_version: ${{ matrix.PHP_VERSION }}

    - name: Run composer tests
      run: composer test

    continue-on-error: true
